/**
 * Client-side redaction utility for exportable artifacts (Draft Email & Lawyer Brief).
 * Redacts phone numbers, email addresses, Indian PAN numbers, Aadhaar numbers,
 * and long digit sequences (e.g. bank accounts, PF account numbers).
 */

export const REDACTION_PATTERNS = {
  // Email addresses
  email: /[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/gi,

  // Aadhaar (12 digits, often grouped in 4-4-4)
  aadhaar: /\b\d{4}[\s-]\d{4}[\s-]\d{4}\b/g,

  // Indian PAN (Permanent Account Number): 5 letters, 4 digits, 1 letter
  pan: /\b[A-Z]{5}[0-9]{4}[A-Z]{1}\b/g,

  // Long digit sequences (11 to 18 continuous digits, e.g. bank accounts, policy numbers)
  longDigits: /\b\d{11,18}\b/g,

  // Indian and international phone numbers (10 digits or with country code)
  phone:
    /(?:(?:\+91[\s-]?)?\b[6-9]\d{9}\b|\b\+?[1-9]\d{0,2}[-\s]?(?:\(\d{1,4}\)|\d{1,4})[-\s]?\d{3,4}[-\s]?\d{3,4}\b)/g,

  // Generic 10-digit identifiers
  genericTenDigits: /\b\d{10}\b/g,
};

export function redactSensitiveData(text: string): string {
  if (!text) return "";

  return text
    .replace(REDACTION_PATTERNS.email, "[REDACTED EMAIL]")
    .replace(REDACTION_PATTERNS.aadhaar, "[REDACTED AADHAAR]")
    .replace(REDACTION_PATTERNS.pan, "[REDACTED PAN]")
    .replace(REDACTION_PATTERNS.longDigits, "[REDACTED NUMBER]")
    .replace(REDACTION_PATTERNS.phone, "[REDACTED PHONE]")
    .replace(REDACTION_PATTERNS.genericTenDigits, "[REDACTED NUMBER]");
}

/**
 * Generates a draft clarification email based on topic findings and questions.
 */
export function generateDraftEmail(
  domainLabel: string,
  topicLabel: string,
  findings: Array<{
    title: string;
    plainSummary: string;
    exactQuote: string | null;
  }>,
  questions: string[],
  redact: boolean
): string {
  const recipientRole = domainLabel.toLowerCase().includes("employee")
    ? "Human Resources / Payroll Team"
    : domainLabel.toLowerCase().includes("housing")
      ? "Landlord / Property Manager"
      : domainLabel.toLowerCase().includes("consumer")
        ? "Customer Support / Merchant Operations"
        : "Relevant Party / Legal Counsel";

  let body = `Subject: Clarification Request: ${topicLabel} Clauses\n\n`;
  body += `Dear ${recipientRole},\n\n`;
  body += `I am writing to seek clarification regarding specific terms in the ${topicLabel.toLowerCase()} documentation provided.\n\n`;

  if (findings.length > 0) {
    body += `I noticed the following terms that I would appreciate clarifying before proceeding:\n`;
    findings.forEach((f, idx) => {
      body += `\n${idx + 1}. ${f.title}:\n   Summary: ${f.plainSummary}\n`;
      if (f.exactQuote) {
        body += `   Referenced excerpt: "${f.exactQuote}"\n`;
      }
    });
    body += `\n`;
  }

  if (questions.length > 0) {
    body += `Specific questions for your clarification:\n`;
    questions.forEach((q) => {
      body += `- ${q}\n`;
    });
    body += `\n`;
  }

  body += `I look forward to your guidance and clarification on these points.\n\n`;
  body += `Sincerely,\n[Your Name]\n[Contact Information]`;

  return redact ? redactSensitiveData(body) : body;
}

/**
 * Generates a structured brief to prepare for consultation with an Indian advocate / legal professional.
 */
export function generateLawyerBrief(
  domainLabel: string,
  topicLabel: string,
  findings: Array<{
    checkId: string;
    title: string;
    severity: string;
    plainSummary: string;
    exactQuote: string | null;
    whyItMatters: string;
    questionToAsk: string;
  }>,
  verifyPointers: string[] | undefined,
  redact: boolean
): string {
  let brief = `LAWYER CONSULTATION BRIEF: ${domainLabel.toUpperCase()} - ${topicLabel.toUpperCase()}\n`;
  brief += `Generated by LawLens Work (Client-side Self-Review)\n`;
  brief += `Notice: Prepared for initial legal consultation. Does not constitute legal advice.\n`;
  brief += `${"=".repeat(70)}\n\n`;

  brief += `1. MATTER OVERVIEW\n`;
  brief += `Domain: ${domainLabel}\n`;
  brief += `Topic: ${topicLabel}\n`;
  brief += `Total Flagged Points: ${findings.length}\n\n`;

  brief += `2. DETECTED ISSUES & CLAUSE EXCERPTS\n`;
  if (findings.length === 0) {
    brief += `No specific risk patterns were flagged by automated checks. General review recommended.\n\n`;
  } else {
    findings.forEach((f, idx) => {
      brief += `[Finding ${idx + 1}] ${f.title} (Severity: ${f.severity.toUpperCase()}, Check: ${f.checkId})\n`;
      brief += `Summary: ${f.plainSummary}\n`;
      if (f.exactQuote) {
        brief += `Verbatim Quote: "${f.exactQuote}"\n`;
      } else {
        brief += `Verbatim Quote: [Clause Missing / Omitted from document]\n`;
      }
      brief += `Indian Context / Why It Matters: ${f.whyItMatters}\n`;
      brief += `Suggested Inquiry: ${f.questionToAsk}\n\n`;
    });
  }

  if (verifyPointers && verifyPointers.length > 0) {
    brief += `3. STATUTORY / COMPLIANCE CHECKLIST\n`;
    verifyPointers.forEach((p) => {
      brief += `[ ] ${p}\n`;
    });
    brief += `\n`;
  }

  brief += `4. CLIENT CONSULTATION GOAL\n`;
  brief += `Request advocate review of the above excerpts against applicable Indian laws (e.g. Indian Contract Act 1872, state Shops and Establishments Acts, RERA/Rent Control Acts, or Consumer Protection Act 2019).\n`;

  return redact ? redactSensitiveData(brief) : brief;
}

/**
 * Prepares deterministic findings for the Negotiation Memo API.
 * CRITICAL PRIVACY BOUNDARY:
 * Strips raw document context and ensures any exact quotes are strictly client-side redacted
 * before network transmission.
 */
export function prepareRedactedFindingsForMemo(
  findings: Array<{
    checkId: string;
    title: string;
    severity: string;
    plainSummary: string;
    exactQuote: string | null;
    whyItMatters: string;
    questionToAsk: string;
  }>
) {
  return findings.map((f) => ({
    checkId: f.checkId,
    title: f.title,
    severity: f.severity,
    plainSummary: f.plainSummary,
    exactQuote: f.exactQuote ? redactSensitiveData(f.exactQuote) : null,
    whyItMatters: f.whyItMatters,
    questionToAsk: f.questionToAsk,
  }));
}
